resources:
  - name: my_repo
    type: GitRepo
    configuration:
      gitProvider: GitHub                         
      path: HKTFrog/NGINX     
      branches:
        include: master

  - name: my_image
    type: Image
    configuration:
      registry: Artifactory                             # <-- replace with your artifactory integration DONE
      sourceRepository: nginx-dev-docker-local                # <-- required if registry is Artifactory DONE 
      imageName: coe.jfrog.io/nginx-dev-docker-local/webgoat # coe.jfrog.io/nginx-dev-docker-local/my      # < -- replace with your image path and name DONE 
      imageTag: latest
      autoPull: true
      
  - name: my_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: my_build
      buildNumber: 1    

  - name: my_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: my_build
      buildNumber: 1
            
pipelines:
  - name: docker_build_push_pipeline
    configuration:
      jfrogCliVersion: 2  
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: my_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: coe.jfrog.io/nginx-dev-docker-local/webgoat
          dockerImageTag: ${run_number}
          inputResources:
            - name: my_repo
          integrations:
            - name: Artifactory                            # <-- replace with your artifactory integration DONE 
        execution:
          onStart:
              # - msg="Run description updated from step $step_id"
              # - update_run_description "$msg"  
              - update_run_description "Add custom text for every run. Example - Build and push Docker image to Artifactory."

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: my_group 
          targetRepository: coe.jfrog.io/nginx-dev-docker-local   
          integrations:
            - name: Artifactory                            # <-- replace with your artifactory integration DONE 
          inputSteps:
            - name: docker_build
          outputResources:
            - name: my_image           

      - name: publish_my_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: my_build_info          